Add Navbar to the website
MLH-Fellowship/pod-4.1.3-portfolio pull request #13
Opened 2021-11-10 08:20 UTC by Shubh4m-B

## Please, go through these steps before you submit a PR.

- [x] My Pod Leader knows I'm working on this Pull Request
- [x] I've explained what the Pull Request is adding.
- [x] I've explained why this is important.

2021-11-10 08:27 UTC, Shubh4m-B commented
We have tried to solve issue #4. The navbar comes into view after the page is scrolled by a certain height.


![Navbar](https://user-images.githubusercontent.com/56843437/141076951-b78688f2-9422-4d3f-85f1-25b7e79be2f1.gif)

2021-11-10 08:28 UTC, Shubh4m-B commented
Also added a hamburger icon for toggling the sidebar.


![Navbar minimized](https://user-images.githubusercontent.com/56843437/141077244-f7b2badc-946b-4393-bf3b-b278495e0941.gif)

2021-11-10 11:18 UTC, grace-omotoso requested changes
Please, see my comments

2021-11-10 11:18 UTC, grace-omotoso commented on Gemfile.lock
> +    thread_safe (0.3.6)
Please, remove Gemlock file changes

2021-11-10 11:18 UTC, grace-omotoso commented on _sass/navbar.scss
> +  //   height: 60%;
remove commented code

2021-11-10 11:18 UTC, grace-omotoso commented on _sass/navbar.scss
> +  margin: auto;
Is this responsive? Did you test on various devices?

2021-11-10 11:18 UTC, grace-omotoso commented on _sass/navbar.scss
> +      // background-color: #74b4fe;
Remove commented code

2021-11-10 11:18 UTC, grace-omotoso commented on _sass/navbar.scss
> +  // background-color: #133667;
remove commented code

2021-11-10 11:24 UTC, grace-omotoso commented
The user experience with this implementation needs to be improved. Users should not have to scroll to a certain height before they see the navbar. I am not able to see the navbar because I use a big screen. The navbar should be displayed immediately after the page is opened.

2021-11-11 07:39 UTC, akshitadixit commented
> The user experience with this implementation needs to be improved. Users should not have to scroll to a certain height before they see the navbar. I am not able to see the navbar because I use a big screen. The navbar should be displayed immediately after the page is opened.

Hi @grace-omotoso we only added the view on scroll only because we found it in the issue #4 description:
>As the portfolio gains more information, it may make sense to add a navigation bar. This bar should include the logo on the left side but only once the page has scrolled down a bit.

2021-11-11 14:03 UTC, closed without merging