Issue #3 and Issue #8
MLH-Fellowship/pod-4.1.3-portfolio pull request #14
Opened 2021-11-10 09:01 UTC by PriyaBihani

## Please, go through these steps before you submit a PR.

- [x] My Pod Leader knows I'm working on this Pull Request
- [x] I've explained what the Pull Request is adding.
- [x] I've explained why this is important.

2021-11-10 09:02 UTC, PriyaBihani commented
In this PR we are trying to solve #3 and #8 issue.

2021-11-10 11:30 UTC, grace-omotoso requested changes
There is a bit of regression here. The project listings have been distorted. Also, device a way to include all the fellows. You don't have to show all of them at once but we can see 3 fellows at a time.

2021-11-10 11:30 UTC, grace-omotoso commented on Gemfile.lock
>        ffi (~> 1.9)
Please, remove gemlock file changes

2021-11-10 20:44 UTC, grace-omotoso commented
@PriyaBihani and co. I am still seeing the regression with the project card. You can compare the project repository on the main branch with what you sent out in the PR. You will see that the project cards do not appear the same way. If you still cannot see the difference, we can have a call together.

2021-11-11 02:50 UTC, PriyaBihani commented
> @PriyaBihani and co. I am still seeing the regression with the project card. You can compare the project repository on the main branch with what you sent out in the PR. You will see that the project cards do not appear the same way. If you still cannot see the difference, we can have a call together.

@grace-omotoso We are working on it. I will contact you, if I don't understand anything.

2021-11-11 03:39 UTC, AdarshNaidu commented
@grace-omotoso please review!! We will ask pod mates to update their respective details once this is merged!

2021-11-11 13:18 UTC, grace-omotoso commented
Great, project cards are no longer distorted. However, I have a concern with displaying all the pod members at once. Would we be doing that if we had 100 pod members? Please, use a carousel instead. Thanks

2021-11-11 18:45 UTC, PriyaBihani commented
@grace-omotoso Added the carousel. Can you check it out?

2021-11-11 23:21 UTC, grace-omotoso commented
@PriyaBihani, it is a lot better, please, fix merge conflicts.

2021-11-11 23:35 UTC, grace-omotoso commented
@PriyaBihani Can we have the location also displayed on the card e.g Murfreesboro, TN, USA. No need to add long and lat

2021-11-12 06:26 UTC, PriyaBihani commented
@grace-omotoso Fixed the merge conflicts and added location, please review.

2021-11-12 11:30 UTC, grace-omotoso commented on _sass/description.scss
> +
remove commented code

2021-11-12 11:30 UTC, grace-omotoso commented on _sass/description.scss
> +		// flex-wrap: wrap;
remove commented code

2021-11-12 12:03 UTC, grace-omotoso approved these changes

2021-11-12 12:03 UTC, merged