Solved Issue #7
MLH-Fellowship/pod-4.1.3-portfolio pull request #15
Opened 2021-11-10 13:30 UTC by saikeshari

## Please, go through these steps before you submit a PR.

- [ ] My Pod Leader knows I'm working on this Pull Request
- [ ] I've explained what the Pull Request is adding.
- [ ] I've explained why this is important.

2021-11-10 13:31 UTC, saikeshari commented
Made the Leaderboard section with static data in the github_details.yml file

2021-11-10 20:28 UTC, grace-omotoso requested changes

2021-11-10 20:28 UTC, grace-omotoso commented on _includes/leaderboard.html
> +    <div class="card-body">
remove commented code

2021-11-10 20:28 UTC, grace-omotoso commented on _data/github_details.yml
> +  PRs: 0
Don't hardcode. Use GitHub API to get the number of PRs on the repository based on a fellow's GitHub username

2021-11-11 13:26 UTC, grace-omotoso requested changes

2021-11-11 13:26 UTC, grace-omotoso commented on _includes/leaderboard.html
> +      // console.log(team.username + " " + index);
remove commented code

2021-11-11 13:26 UTC, grace-omotoso commented on _includes/leaderboard.html
> +    // console.log(team.username1);
remove

2021-11-11 13:26 UTC, grace-omotoso commented on _data/github_details.yml
> +  username1: Adarsh Naidu
Do we still need this since you are no longer hardcoding? Please, remove if no longer needed

2021-11-11 18:38 UTC, grace-omotoso approved these changes

2021-11-11 18:40 UTC, grace-omotoso commented
@saikeshari looks good to me but I have one more ask. Can you move it above the Projects section and below the Meet the Pod section? Thanks

2021-11-11 18:43 UTC, saikeshari commented
Done!

2021-11-11 18:46 UTC, grace-omotoso approved these changes

2021-11-11 18:46 UTC, merged